[package]
name = "auth-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
# JWT handling
jsonwebtoken = "9.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# HTTP client for JWKS
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }

# Error handling
thiserror = "1.0"

# Base64 decoding
base64 = "0.22"

# Async trait
async-trait = "0.1"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Caching (optional)
lru = "0.12"

[dev-dependencies]
tokio-test = "0.4"
